---
- hosts: all
  become: true
  tasks:

  - name: install apache2 and libapachae2-mod-php packages
    ansible.builtin.package:
      name: 
        - "{{ apache_package }}"
        - "{{ php_package}}"
      state: latest
      update_cache: yes
